# play level variables
- name: variables from Inventory level
  hosts: localhost
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hi, I am learning {{Course}}, Tainer is {{Trainer}}, Duration is {{Duration}}"
